### ISSUE TITLE
Xamarin Support for Kontakt Android API 

### ISSUE THREAD

**Issue by DavePilks** [jamesmontemagno/iBeaconsEverywhere#2]
Hi

I have been trying to bind this API for a while now and I cant seem to get it right. It doesnt gen the files properly.

I see that you didnt use this API in your Android Solution. Does the Estimote package allow the android device to use the Kontakt beacons? 

iOS isnt a problem because of iBeacon but I cannot get this working.

**Comment by jamesmontemagno** [comment]
You can use any beacon with the estimote sdk. Just pass it the UUID.

**Comment by AshwiniBokade** [comment]
I want to use kontakt.io beacons in xamarin forms but I did not get any refrence to related implementaion through estimote sdk.
Can you please suggest what step I follow to implement beacon in xamarin forms.
